### ISSUE TITLE
raise NotImplementedError() ---> velo_ok = self.__velo_control_loop()

### ISSUE THREAD

**Issue by seivazi** [dougsm/mvp_grasp#12]
Hi @dougsm 

When I run rosrun mvp_grasping panda_mvp_grasp.py I get following error:
  
File "/catkin_ws/src/mvp_grasp/mvp_grasping/ros_nodes/panda_mvp_grasp.py", line 62, in <module>
    agc.go()
  File "/catkin_ws/src/mvp_grasp/mvp_grasping/src/mvp_grasping/panda_base_grasping_controller.py", line 327, in go
    velo_ok = self.__velo_control_loop()
  File "/catkin_ws/src/mvp_grasp/mvp_grasping/src/mvp_grasping/panda_base_grasping_controller.py", line 256, in __velo_control_loop
    raise NotImplementedError()
NotImplementedError

At the same time backend throw a long error:

[ERROR] [1581502337.956858]: Error processing request: 2 root error(s) found.
  (0) Failed precondition: Error while reading resource variable width_out/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/width_out/bias/N10tensorflow3VarE does not exist.
	 [[{{node width_out/BiasAdd/ReadVariableOp}}]]
	 [[sin_out/BiasAdd/_39]]
  (1) Failed precondition: Error while reading resource variable width_out/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/width_out/bias/N10tensorflow3VarE does not exist.
	 [[{{node width_out/BiasAdd/ReadVariableOp}}]]
0 successful operations.
0 derived errors ignored.
['Traceback (most recent call last):\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 629, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/seivazi/catkin_ws/src/mvp_grasp/mvp_grasping/ros_nodes/grasp_entropy_node.py", line 128, in update_service_handler\n    points, angle, width_img, _ = predict(depth_crop, process_depth=False, depth_nan_mask=depth_nan_mask)\n', '  File "/home/seivazi/catkin_ws/src/mvp_grasp/ggcnn/src/ggcnn/ggcnn.py", line 67, in predict\n    pred_out = model.predict(depth.reshape((1, 300, 300, 1)))\n', '  File "/home/seivazi/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 1078, in predict\n    callbacks=callbacks)\n', '  File "/home/seivazi/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 363, in model_iteration\n    batch_outs = f(ins_batch)\n', '  File "/home/seivazi/.local/lib/python2.7/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__\n    run_metadata=self.run_metadata)\n', '  File "/home/seivazi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1458, in __call__\n    run_metadata_ptr)\n', 'FailedPreconditionError: 2 root error(s) found.\n  (0) Failed precondition: Error while reading resource variable width_out/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/width_out/bias/N10tensorflow3VarE does not exist.\n\t [[{{node width_out/BiasAdd/ReadVariableOp}}]]\n\t [[sin_out/BiasAdd/_39]]\n  (1) Failed precondition: Error while reading resource variable width_out/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/width_out/bias/N10tensorflow3VarE does not exist.\n\t [[{{node width_out/BiasAdd/ReadVariableOp}}]]\n0 successful operations.\n0 derived errors ignored.\n']

**Comment by seivazi** [comment]
I guess I found out where the error comes from:
https://stackoverflow.com/questions/14898197/override-private-method-in-python
I will test it tomorrow.

**Comment by dougsm** [comment]
Hmm yeah I think I probably goofed up some code refactoring here.  Just change all of the double underscore to single underscore and you'll be good.
