### ISSUE TITLE
AttributeError: 'Pose' object has no attribute 'pose'

### ISSUE THREAD

**Issue by seivazi** [dougsm/mvp_grasp#13]
In the panda_base_grasping_controller.py:

self.best_grasp.position.z = max(self.best_grasp.pose.position.z - 0.01, 0.026) 

AttributeError: 'Pose' object has no attribute 'pose'

Shouldn't be without pose? like this: self.best_grasp.position.z = max(self.best_grasp.position.z - 0.01, 0.026) 

I get similar error for self.pc.set_gripper(self.best_grasp.width, wait=False) because there is no width. 

Am I missing something?

**Comment by dougsm** [comment]
Can you tell me which scripts you are running? I assume that it's expecting best_grasp to be a `Grasp` type message, which does have all of those attributes.

**Comment by seivazi** [comment]
Thank you! The error is not any more valid since I fixed _velo_control_loop.
