### ISSUE TITLE
How to set bounds in mvp_grasp.yaml?

### ISSUE THREAD

**Issue by seivazi** [dougsm/mvp_grasp#15]
Hi,
I'm confused about bounds in mvp_grasp.yaml. I try to change them but either I get out of bounds error or some dimension miss match error. 

I use  this_pose = self.active_group.get_current_pose() to find my desire pose and save it as 
self.active_group.remember_joint_values('grip_ready', this_pose) 

If I keep your setting for bounds the robot moves but very far from my  grip_ready location.

Have you hard cord the searching position somewhere in the code?

In panda_base_grasping_controller.py why do you have two initial position?
            self.pc.goto_named_pose('grip_ready', velocity=0.25)
            start_pose = list(self.pregrasp_pose)
            start_pose[0] += np.random.randn() * 0.05
            start_pose[1] += np.random.randn() * 0.05
            self.pc.goto_pose(start_pose, velocity=0.25)

The way understood the bounds is set around grip_ready position. I can make this two working but out of bounds error seems to come from update_grid.

Any suggestion?

**Comment by dougsm** [comment]
The histogram bounds in mvp_grasp.yaml are defined in world coordinates in the robot base frame.  In my case, I believe the workspace was to the right of the robot (negative y direction), so if you are working in front of the robot (positive x direction) then you will need to adjust them accordingly.
It is also expecting the area to be a square, if that helps.
