### ISSUE TITLE
How to apply the model in ggcnn repository to this repository 

### ISSUE THREAD

**Issue by honghongzhenbang** [dougsm/mvp_grasp#18]
I noticed that you use torch, keras in ggcnn repository ,but tensorflow.keras in this. 
Can the model trained in ggcnn repository be applied in this repository?
If I want to train a model with ggcnn repository , how do I apply it in here?
Since I saw the model in this repository trained for 29 epochs, is it necessary to continue training?

thank you!

**Comment by dougsm** [comment]
G'day @honghongzhenbang 
Sorry, I've been meaning to fix that for a while.  There is the code there to run using the torch version of the network: https://github.com/dougsm/mvp_grasp/blob/master/ggcnn/src/ggcnn/ggcnn_torch.py
For the time being, you'll just need to change the import from:

https://github.com/dougsm/mvp_grasp/blob/c301ba2f4b0c0fb0c92b61a34f2821e56c693163/ggcnn/ros_nodes/ggcnn_service.py#L15

to `from ggcnn.ggcnn_torch import predict, process_depth_image`
