### ISSUE TITLE
missing hidapi in requirements

### ISSUE THREAD

**Issue by seivazi** [dougsm/mvp_grasp#2]
I got missing hidapi error which can be fixed by  sudo apt-get install libhidapi-dev

**Comment by dougsm** [comment]
Hi @seivazi 
Thanks for pointing this out!  I've updated the readme and added a little more installation information to the scales_interface package.  The scales_interface package is only required if you happen to have compatible scales, so I've made it ignored by default.

**Comment by seivazi** [comment]
Thank you for fast reply.
Now I get following error: COULDNT CONNECT TO SCALES
I checked the VID and PID and both are the same as yours. I also change the serial number in scales.launch with the one behind my scale. At least for me I can not get Serial number in ubuntu. Is it same for you?
Do I need to enable something in ubuntu for Hidapi to be able to read the scale or open USB. There seems to be two implementations for Hidapi now I wonder about sudo apt-get install libhidapi-dev :)

Here is full error:

 INFO] [1578586778.042945732]: Serial number received: 1061935027101
046a 0011 (null)
1532 0510 (null)
0922 8003 (null)
04d9 a086 (null)
062a 4102 (null)
[ WARN] [1578586778.043661421]: COULDNT CONNECT TO SCALES
[scales-2] process has finished cleanly

**Comment by dougsm** [comment]
That's a difficult one to debug... I'm not 100% sure, but there are a few things you can try.

1. The device should appear as `/dev/hidraw#` where # is a number that you'll need to figure out.  You should be able to `sudo cat /dev/hidraw#` and have nonsense data printed to the screen.
2. Depending on the ubuntu version, you may require udev rules.  Try adding `SUBSYSTEM=="usb", ACTION=="add", MODE="0664", GROUP="plugdev"` to a file `/etc/udev/rules.d/50-usbdevice.rules`
3. Double check serial number reported by the scales using `lsusb -v`

Hope one of those helps :-)

**Comment by seivazi** [comment]
Thank you for the help. I try everything but I can't get serial number of DYMO. lsusb -v only gives me "3" for serial number :) However I maned to pass the error by replacing NULL instead of serial number in hid_open. It seems working now.
