### ISSUE TITLE
size and scale of the adversarial object from DexNet?

### ISSUE THREAD

**Issue by Assets01** [dougsm/mvp_grasp#20]
Hello! I wonder the size and scale of the adversarial used in the grasping, for example, the figure bellow shows one object I downloaded from DexNet, is this size (in mm) same with what you used in your work, or you rescaled it?
![捕获](https://user-images.githubusercontent.com/56440761/90487238-c53c4380-e16c-11ea-836f-4f3368620293.PNG)

**Comment by dougsm** [comment]
I don't have the actual object with me so can't check, but those numbers seem about right.  I don't recall rescaling them in any way.

**Comment by Assets01** [comment]
> I don't have the actual object with me so can't check, but those numbers seem about right. I don't recall rescaling them in any way.

Thank you for your reply, I will try the original size.
