### ISSUE TITLE
Kinova

### ISSUE THREAD

**Issue by phuicy** [dougsm/mvp_grasp#21]
Just as a note, I have got this working for Kinovas.
I will work to tidy it up, and push up.

thanks,
Guy

**Comment by Assets01** [comment]
looking forward to it

**Comment by Assets01** [comment]
> Just as a note, I have got this working for Kinovas.
> I will work to tidy it up, and push up.
> 
> thanks,
> Guy
Hi! I aslo tried to reproduce this work with a kinova robot, but encountered many problems. so I am looking forward to your modifications.

**Comment by mkt1412** [comment]
Hi, is the implementation for KINOVA available now? Really look forward to that.
