### ISSUE TITLE
How to get the camera pose in robot frame

### ISSUE THREAD

**Issue by alisonjpp** [dougsm/mvp_grasp#27]
when the camera is mounted on the wrist, how to get the camera frame relative to the robot arm?

**Comment by dougsm** [comment]
The best way is to have a calibration set-up with a checkerboard in a known position, and use an existing library such as http://wiki.ros.org/camera_calibration to perform the calibration.  Alternatively, you can model it in CAD, and measure the distances. This is less accurate, but probably good enough.

**Comment by alisonjpp** [comment]
Thanks!

**Comment by caijunhao** [comment]
Hi dougsm,
 
Have you ever measure the ideal transformation between the RGB camera of the D435 and the end effector of Franka in CAD?

**Comment by bibbygoodwin** [comment]
@caijunhao , did you arrive at a good estimate for that transformation? Thanks!
