### ISSUE TITLE
unused args [infra2_width,...

### ISSUE THREAD

**Issue by seivazi** [dougsm/mvp_grasp#3]
Hi,
I'm trying to replicate your experiment.
When running: roslaunch mvp_grasping wrist_realsense.launch
I got "unused args [infra2_width,..." error which seems to be fixed by commenting those argument from wrist_realsense.lunch file. Please correct me if I'm wrong. 

Now roslaunch mvp_grasping wrist_realsense.launch seems to run services but at the end I get following:
- 09/01 15:27:46,757 WARNING [140586694735616] (ds5-timestamp.cpp:76) UVC metadata payloads not available. Please refer to the installation chapter for details.
Waiting for service /camera/realsense2_camera_manager/set_parameters...
- 09/01 15:28:38,078 WARNING [140586550888192] (types.cpp:49) Out of frame resources!
- 09/01 15:28:38,078 ERROR [140586550888192] (synthetic-stream.cpp:47) Exception was thrown during user processing callback!

Do you get similar message in your side? The camera (D435) seems to be working with realsense_viewer

P.s.
I'm new to ROS so any extra instruction will be more than welcome. Meanwhile I will proceed with running other parts :)

Cheers,

**Comment by dougsm** [comment]
It looks like intel changed the parameters in the Realsense launch file between different versions -- you are completely correct to simply comment out those parameters.  Are you able to submit a pull request with the fixed launch file? 

I don't get those warnings, but I do get some other warnings. At the end of the day, I think as long as the data is coming through then it's fine.

**Comment by seivazi** [comment]
I will submit a pull request once I mange to run whole system :)

**Comment by seivazi** [comment]
There is another problem with wrist_realsense.lunch file it is missing   <arg name="tf_prefix"           default="$(arg camera)"/> which causes error in tf
