### ISSUE TITLE
serialization error: model file missing

### ISSUE THREAD

**Issue by seivazi** [dougsm/mvp_grasp#5]
Hi Doug,

You have "epoch_29_model.hdf5" file here but I found also epoch_24_iou_0.82_morezoom file. Which one should we use? Using "epoch_29..." throw following error:

anaconda3/envs/mvp2/lib/python2.7/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
cPickle.UnpicklingError: invalid load key, 'H'.

**Comment by dougsm** [comment]
epoch_29_model.hdf5 is the correct file.  Which version of tensorflow are you using? Sounds like it could be a version issue.  The model was probably created with an older version of TF.

**Comment by seivazi** [comment]
I'm using Tensorflow 1.11 and tf.keras.version: 2.1.6-tf. What I found so far. You have two version of ggcnn:

ggcnn.py : 
calling to "epoch_29_model.hdf5" cause following error: 
.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/saving.py", line 251, in load_model
    training_config['weighted_metrics'])
KeyError: 'weighted_metrics'

Error seems to be related of Tensorflow and tf.keras.version. Which version did you use for saving the model? I found https://stackoverflow.com/questions/52753846/error-in-load-a-model-saved-by-callbakcs-modelcheckpoint-in-keras solution but not sure. 

ggcnn_torch.py:
I guess we should not use "epoch_29_model" here and that cause previous error anaconda3/envs/mvp2/lib/python2.7/site-packages/torch/serialization.py", line 532, in _load
magic_number = pickle_module.load(f)
cPickle.UnpicklingError: invalid load key, 'H'.
Do you have a separate model for torch version?

**Comment by aPonza** [comment]
With HDFView I can see the model epoch_29_model.hdf5 was created with keras 2.0.8 which seems to be included in tensorflow 1.4.0. I changed the version in requirements and installed 1.4, verified and indeed `keras.__version__ = 2.0.8-tf`, but the error persists, so 'H' is still an invalid key.

**Comment by seivazi** [comment]
Thank you for checking on this. Is epoch_29_model.hdf5 suppose to work for both  ggcnn.py and ggcnn_torch.py?

**Comment by aPonza** [comment]
AFAIK hdf5 models are compatible with pytorch, if that's what you mean, but I definitely don't understand the error message, and why both torch and keras are used in the same project.

**Comment by dougsm** [comment]
Hello,

The hdf5 model supplied is for the tensorflow/keras implementation.  This version (i.e. the version in ggcnn.py) is what should be running, and is what is being imported by the ROS node.

The ggcnn_torch.py file is for compatibility with the updated ggcnn repository (https://github.com/dougsm/ggcnn) which has been ported to pytorch, but I have not supplied a model for this.  pytorch by default uses pickled save files, not hdf5.

Judging by your issues, it looks like the problem is that you are trying to import a keras model using pytorch.

> ggcnn_torch.py:
I guess we should not use "epoch_29_model" here and that cause previous error anaconda3/envs/mvp2/lib/python2.7/site-packages/**torch**/serialization.py", line 532, in _load
magic_number = pickle_module.load(f)
cPickle.UnpicklingError: invalid load key, 'H'.

The .hdf5 model can be imported using tensorflow==1.15.0 as per the requirements.txt file (and possibly other versions depending on compatibility):

```
Python 2.7.17 (default, Nov 27 2019, 11:02:25) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow.__version__
'1.15.0'
>>> tensorflow.keras.__version__
'2.2.4-tf'
>>> from tensorflow.keras.models import load_model
>>> load_model('models/epoch_29_model.hdf5')

<-- lots of output from tensorflow -->

<tensorflow.python.keras.engine.training.Model object at 0x7fd1942e6810>
```

**Comment by aPonza** [comment]
> the problem is that you are trying to import a keras model using pytorch

Yup, that's what's happening. From the README:

```
# Start the Multi-View Picking backend
roslaunch mvp_grasping grasp_entropy_service.launch
```

This [launches grasp_entropy_node.py](https://github.com/dougsm/mvp_grasp/blob/48330d45a135a5cf1bb058909ed1323be200069f/mvp_grasping/launch/grasp_entropy_service.launch#L4) which [uses the torch implementation](https://github.com/dougsm/mvp_grasp/blob/48330d45a135a5cf1bb058909ed1323be200069f/mvp_grasping/ros_nodes/grasp_entropy_node.py#L17).

Removing `_torch` from said line, I had to update back to tensorflow 1.14.0 (1.15.0 doesn't exist according to my pip, and I usually am very wary of upgrading pip but that might be the solution to that) and now it all seems to work. I'll add the microfix to the hotfix branch in PR #6

**Comment by seivazi** [comment]
Thank @aPonza! I will try it on Monday.

**Comment by dougsm** [comment]
@aPonza ah of course, that's my bad.  I was looking in the two ggcnn nodes, didn't remember that it was used elsewhere. Thanks for the fix!

**Comment by seivazi** [comment]
Hi @dougsm 
Which dataset did you use to train your model? is it based on JACQUARD DATASET?

**Comment by aPonza** [comment]
You can read section 4.B in [his paper](https://arxiv.org/pdf/1804.05172.pdf) which is referred to in [his other paper](https://arxiv.org/pdf/1809.08564.pdf) as the used CNN.

**Comment by seivazi** [comment]
Thank you @aPonza for the hint. It seems to be Dexnet, ACRV, and YCB but
what confused me is the https://github.com/dougsm/ggcnn/tree/master/utils/data with the python file for Cornell and Jacquard dataset.

**Comment by dougsm** [comment]
The model was originally trained on Cornell dataset, as per [Closing the loop for robotic grasping](https://arxiv.org/pdf/1804.05172.pdf).  The Jacquard dataset came out after this paper was published.
We added the Jacquard daset in [the extended version of the paper](https://journals.sagepub.com/doi/full/10.1177/0278364919859066).

**Comment by seivazi** [comment]
For comparison do you have trained model for each dataset separately. E.g. a hdf5 file that is trained only with Cornell dataset,....
