### ISSUE TITLE
Franka Emika installation

### ISSUE THREAD

**Issue by seivazi** [dougsm/mvp_grasp#7]
I'm confused about installing Franka Emika. Do i need to Set up the real-time kernel?

I'm following their instruction https://frankaemika.github.io/docs/installation_linux.html for franka_ros but having some error and wonder about real-time kernel because It seems NVIDIA binary drivers are not supported on PREEMPT_RT kernels.

**Comment by dougsm** [comment]
Yes, as far as I know you will require the real time kernel for the franka emika.
I don't know about the compatibility with the NVIDIA drivers, but if it helps, I usually run the GGCNN inference, realsense camera, scales etc. on a separate PC, with a dedicated computer with the RT kernel for controlling the robot.

**Comment by seivazi** [comment]
Thank @dougsm for the advise with the second computer. I will do the same. 
Do I need to change something in your ROS wrapper in order to get connected to the second machine (which connected to robot)? Should franka_control_wrappers moved to that machine?

P.s.
Sorry for so many questions. You have done a great work. Hopefully, these discussions make it easier for beginners like me to start and contribute.

**Comment by mkt1412** [comment]
> Thank @dougsm for the advise with the second computer. I will do the same. Do I need to change something in your ROS wrapper in order to get connected to the second machine (which connected to robot)? Should franka_control_wrappers moved to that machine?
> 
> P.s. Sorry for so many questions. You have done a great work. Hopefully, these discussions make it easier for beginners like me to start and contribute.

Hi, I'm facing the same problem. Have you solved it? Thanks!

**Comment by seivazi** [comment]
> 

It is possible to split the project to multiple PCs. However for simplicity you might just clone the whole repo in both PC and just run relevant services in your target PC.
